= Publisher

Generate, serve and publish websites.

== Motivation

=== Jekyll finally pissed me off

When I listed TODO link  unresistable to any programmer urge to
write certain kinds of systems, I neglected to mention
a static site generator.

I've been using Jekyll since I migrated my blog from Blogger TODO when;
I then moved my notes from Roam into Obsidian
TODO when link and merged them into the static site with my blog;
that required customizing my Jekyll setup
TODO move Jekyll customization notes into the Jekyll page and link it here.

In March 2026, my site stopped publishing;
error messages were meaningless, and it took a lot of time
to figure out what is the problem by deleting files until it went away.
It turned out that Jekyll plugin I used for handling wiki links TODO link
breaks when an `index` page contains a wiki link (e.g., a [[TODO]]).
Previous communications with the author of the plugin made it clear
that he considers Jekyll to be a legacy system
(but it remained unclear what is the suggested replacement).

At this point, I looked at a few of the modern static site generators
like 11ty TODO link - and decided to write my own ;)

=== New Possibilities

It occurred to me that if I write my own site generator,
I can make it Obsidian-aware:

- it can read Obsidian configuration
- it can publish daily notes as dated blog posts

It also occurred to me that I can make alter-rebbe.org TODO link,
a site where I publish some archive documents in the TEI format
static (again) -
if I add support for TEI to my generator:

- link resolution
- facsimiles
- multi-lingual names

It also occurred to me that I can add publishing to X Articles -
if X ever makes an API for that. This would allow me
to own my blog - and at the same time use X ;)

== Approach

=== Opinionated

Since I am writing this site generator for my own use,
it is going to be opinionated:

- everything is written in Scala
- no plugins
- no SCSS
- no template languages
- no layouts

TODO expound

=== ZIO Blocks

At exactly the same time I became aware of the ZIO Blocks project,
which just added support for a few data formats that I need.

== Markdown

Pipeline:

- Markdown text
- Markdown AST
- HTML text
- HTML AST

I need HTML AST for post-processing like chunking,
and prefer to use it for all post-processing
like HTML layout for the browser and PDF generation.

Since Markdown allows embedding HTML,
ans since opening and closing tags of the same HTML element
may end up in different Markdown AST nodes,
I can not go directly from Markdown AST to HTML AST -
I have to go through HTML text.

Industry-standard FlexMark parser can be configured to
pair some - but not all - of the tags,
so direct Markdown AST to HTML AST is not possible with FlexMark either.

Since I insist on the end result being HTML AST,
invalid XML (e.g., unclosed 'br' elements)
embedded in the Markdown text is not supported.

WOW! It turns out that ZIO Block Markdown parser
parses nested lists incorrectly:

[source]
----
- l1
  - l2
----

parses exactly the same as

[source]
----
- l1
- l2
----

So, it seems that I *have* to use FlexMark after all...

== TODO

Config:

- get `Config.dailyNotesDirectoryName` out of `.obsidian/daily-notes.json/folder`
- make inclusion of `_drafts` configurable

Wiki links in Obsidian:

- are they case-sensitive?
- do they take into account file name, title property, document title?
- how do they look in the file if name reference is ambiguous?
- can they be split between the lines?
- do they support |?
- do they support any kind of agglutination?
- categories can be wiki links?!
- handle permalinks and multi-name redirects

CLI:

- use ZIO CLI
- set log level from the CLI option
- serve with filesystem watch
- publish site into a bucket
- package as a stand-alone executable
- package as a GitHub Action

Additional markup types:

- TEI (including facsimiles and raw TEI)
- AsciiDoc?
- DocBook??
- ReStructured Text?

PDF:

- danfickle/openhtmltopdf: An HTML to PDF library for the JVM. Based on Flying Saucer and Apache PDF-BOX 2. With SVG image support. Now also with accessible PDF support (WCAG, Section 508, PDF/UA)! · GitHub [https://share.google/UiGeZVUcInZur8zNF](https://share.google/UiGeZVUcInZur8zNF)
- [https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd](https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd)
