= Static Site Publisher
:toc:
:toclevels: 4
:toc: preamble
:icons: font

Generate, serve and publish websites.

[#summary]
== Summary

[#features]
== Features

TODO table of Markdown features with FlexMark extensions and Obsidian plugins.

== Farewell, Jekyll

Events of 2026:

- Mar 17: My Jekyll setup (wiki-refs plugin) broke down
- Mar 20: I created my site publisher repository
- I became aware of ZIO Blocks Yaml released on Mar 11 and ZIO Blocks Markdown released on Jan 30
- Mar 22: I filed ZIO Blocks pull request
- Apr 30: I switched my personal website to use my site publisher vis GitHub Actions Workflow
- May 04: I removed all traces of Jekyll from my personal website
- May 06: I became aware of the ZIO Blocks HTML that was added on Apr 25-May 01, and started switching to it from my home-grown HTML DSL
- May 07: switched


First milestone for this project is to replace Jekyll on my personal website.
In under two month and a little less than 2000 lines of Scala code,
I have:

- no support for paginating the post list, which I did not use with Jekyll anyway;
- instead of the Ruby code highlighter Rouge, my publisher uses Highlights.js; it loads only the language modules used in the page; TODO unsupported language mapping...

- while I did manage to list children pages using Jekyll,
I never figured out how to list subdirectories;
with my own publisher this is not a problem ;)

- Jekyll ignores Markdown files without front matter; I do not;
- wiki links
- link resolution
- front-matter defaults auto-added pages;
- header pages are configured in their frontmatter, with FA icons (and defaults) ;)
- transclusion
- directory navigation: up, prev, next;
- path navigation;
- insertion of missing index pages;

Write about all the plugins I used:

- jekyll-optional-front-matter
- jekyll-sitemap
- jekyll-feed
- jekyll-mentions
- jekyll-avatar
- jekyll-wikirefs

[#future]
== Future

=== Title

Match pages by explicit titles too.

For documents that have titles in the body and not in front matter (like in TEI), transplant them into the layout-appropriate place.

=== Pages
- file named after a directory is its index!
- handle categories; they can be wiki links?!
- auto-create category pages
- auto-create tag pages
- handle permalinks and multi-name redirects

=== Transclusion
Sort the pages in transclusion order, extract the sections and block,  transclude, and style the transclusions

=== Chunking and Paging
- implement splitting of HTML by section when front matter has `chunk: true`
- implement paging of the long lists (e.g., list of posts)

=== PDF
Generate PDF when front-matter says `pdf: true`

- danfickle/openhtmltopdf: An HTML to PDF library for the JVM. Based on Flying Saucer and Apache PDF-BOX 2. With SVG image support. Now also with accessible PDF support (WCAG, Section 508, PDF/UA)! · GitHub[https://share.google/UiGeZVUcInZur8zNF](https://share.google/UiGeZVUcInZur8zNF)
- [https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd](https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd)

=== More Markup Languages

- TEI (including facsimiles and raw TEI)
- AsciiDoc

- DocBook??
- ReStructured Text?

=== CLI
- package as a GitHub Action
- serve with filesystem watch
- publish site into a bucket

=== Autoposting
- add FrontMatter "post: true" to control publishing arbitrary notes as posts
- add publishing and updating a page to X once X API supports Articles

=== Further Research

Add admonitions/asides/callouts support in a way that works for both FlexMark and Obsidian.

Look at https://stephango.com/vault

Look at https://squidfunk.github.io/mkdocs-material/

Look at https://github.com/KaTeX/KaTeX[KaTeX] as a MathJax alternative...

Think about serializing the full list of back-links out of the memory

Maybe use FlexMark to convert wiki-links without resolving them (and lose support for wiki links in TEI)

Maybe configure FlexMark to not convert general transclusion Markdown links (if it does now)

[#motivation]
== Motivation

=== Jekyll finally pissed me off

When I listed TODO link  unresistable to any programmer urge to
write certain kinds of systems, I neglected to mention
a static site generator.

I've been using Jekyll since I migrated my blog from Blogger TODO when;
I then moved my notes from Roam into Obsidian
TODO when link and merged them into the static site with my blog;
that required customizing my Jekyll setup
TODO move Jekyll customization notes into the Jekyll page and link it here.

In March 2026, my site stopped publishing;
error messages were meaningless, and it took a lot of time
to figure out what is the problem by deleting files until it went away.
It turned out that Jekyll plugin I used for handling wiki links TODO link
breaks when an `index` page contains a wiki link (e.g., a [[TODO]]).
Previous communications with the author of the plugin made it clear
that he considers Jekyll to be a legacy system
(but it remained unclear what is the suggested replacement).

At this point, I looked at a few of the modern static site generators
like 11ty TODO link - and decided to write my own ;)

=== Titles and File Names
Jekyll relies on page titles being given explicitly in the front matter
and ignores the file names; I had to use a TODO Obsidian plugin to set the
titles from the file names to communicate them to Jekyll;
as a result, pages where the title is different from the file name
(e.g., `index` pages)
had to be marked with TODO in their front matter to disable this plugin
from setting the front matter title.

My plugin uses both the front matter title and the file name for
link resolution, so I can remove this Obsidian plugin and
redundant front matter titles which are the same as the file name,
and set the title in the front matter only when it is different from the file name.

Obsidian uses file names exclusively and ignores the front matter title;
for link resolution to use front matter titles also,
TODO Obsidian plugin needs to be installed.

Wiki links in Obsidian:

- are they case-sensitive?
- do they take into account file name, title property, document title?
- how do they look in the file if name reference is ambiguous?
- can they be split between the lines?
- do they support any kind of agglutination?

=== New Possibilities

It occurred to me that if I write my own site generator,
I can make it Obsidian-aware:

- it can read Obsidian configuration
- it can publish daily notes as dated blog posts

It also occurred to me that I can make alter-rebbe.org TODO link,
a site where I publish some archive documents in the TEI format
static (again) -
if I add support for TEI to my generator:

- link resolution
- facsimiles
- multi-lingual names

It also occurred to me that I can add publishing to X Articles -
if X ever makes an API for that. This would allow me
to own my blog - and at the same time use X ;)

=== Opinionated

Since I am writing this site generator for my own use,
it is going to be opinionated:

- everything is written in Scala
- no plugins
- no SCSS
- no template languages
- no layouts

TODO expound

[#implementation]
== Implementation

At exactly the same time I became aware of the ZIO Blocks project,
which just added support for a few data formats that I need.

=== JSON
I use ZIO Blocks JSON support to read Obsidian configuration files.

=== Yaml
- pester ZIO Blocks people to fix the hard-coded kebab-case bug (https://github.com/dubinsky/site-publisher/issues/6)
- report to ZIO Blocks people enumeration handling bug (https://github.com/dubinsky/site-publisher/issues/7)
- my stashed extra keys will not survive round trip once FrontMatter becomes a case class and `.copy()` is used!
- besides, I stash keys other than the ones in the schema of the `Config`
class, but the codec changes the names: currently - because of the kebab bug, but even once it is fixed, a name mapper could be in effect...

=== Markdown

Pipeline:

- Markdown text
- Markdown AST
- HTML text
- HTML AST

I need HTML AST for post-processing like calculating page structure, resolving links to sections and blocks, transclusion, chunking, adding TOC,
and prefer to use it for all post-processing
like HTML layout for the browser and PDF generation.

Converting ZIO Blocks Markdown AST to XML AST proved inconvenient
(e.g., for reasons unknown, there are two flavours of each `Inline` subclass); it also turned out to be impossible, since
Markdown allows embedding HTML,
and since opening and closing tags of the same HTML element
may end up in different Markdown AST nodes,
I can not go directly from Markdown AST to HTML AST -
I have to go through HTML text.

Parsing Markdown with ZIO Blocks parser and writing it to XML text
turned out to be inconvenient: ZIO Blocks Markdown writer
produces unclosed tags like `br` and `hr`,
which are not valid XML and thus can not be parsed into XML AST.
I had to write my own writer for ZIO Blocks Markdown AST.

Converting Markdown text to XML AST using ZIO Blocks Markdown parser
still turned out impossible, since it parses nested lists incorrectly - see https://github.com/zio/zio-blocks/issues/1377.

FlexMark WikiLink extension is useless to me:
- it sets the content of the rendered HTML 'a' element when there is no | in the link;
- it prefixes the href with the dashes corresponding in number to the spaces after the |...

Unlike ZIO Blocks Markdown HTML renderer,
which I had to fork to ensure that resulting HTML is valid XML
(no unclosed tags like 'br', 'hr', 'input' and 'img'; attributes have values etc.),
FlexMark renders valid XML out of the box.
I may need to add some extensions to handle GitHub task lists and such...

I had to switch to the industry-standard FlexMark parser.

It can be configured to
pair some - but not all - of the tags,
so direct Markdown AST to HTML AST is not possible with FlexMark either.

Since I insist on the end result being HTML AST,
invalid XML (e.g., unclosed 'br' elements)
embedded in the Markdown text is not supported.

I process wiki links and Kramdown TOC marker in post-processing.

On May 12, 2026 I found out that ZIO Blocks XML parser
`zio.blocks.schema.xml.XmlReader`
is *useless*: it chokes on entities other than `amp`, `lt`, `gt`, `quot` and `apos`! Fucking amateur hour! I have to switch to something standard and convert the result to ZIO Blocks XML AST; SAX or StAX?

=== XML

As a part of the OpenTorah project, I developed a custom
XML pretty-printer for the Scala XML AST;
I need to write one for the ZIO Blocks XML AST,
since the XML writer provided by ZIO Blocks is broken:
when used with "pretty", it

- inserts spaces between book titles and quotes around them;
- destroys the formatting of the code blocks;

when used with "default", in addition to producing
non-human-readable text, it:

- does not insert spaces between text and elements;
- mangles the formatting of the code blocks if there are spaces at the beginning of the lines after the first one.

With my own XML writer, I can also ensure that the empty elements
that cause problems with the browsers when they are self-closed
(script, data, span) are not -
without inserting comments into them, which is ugly.

- I think I should not have to cling quotes and friends to the sibling elements unless either FlexMark writer or XML parser introduce spurious whitespace; if it is the XML parser, and if it really shouldn't, integrate with the industry-standard parser...

See that the following renders as is:

[source,markdown]
----
val escaped = userInput.replace("<", "&lt;").replace(">", "&gt;")
----

On May 12, 2026, while attempting to add FlexMark extensions "Footnotes" and "GFM Task List", I discovered that ZIO Blocks XML
parser chokes on HTML entities like  `&nbsp;`, which the Task List extension
outputs, and alone `&#8617;` ("right arrow curling left emoji")
which the Footnote extension does.
There is no way to turn off entity parsing in the ZIO Blocks XML parser.

I wrote an adaptor that uses StAX XML parse built into the JDK
and produces ZIO Block XML AST. It takes less than a 100 lines
of code.
TODO share with the ZIO Blocks people.

StAX XML parser, just like the ZIO Blocks XML parser,
does not recognize HTML entities - but it can be configured
to not expand the entities, and instead deliver them via StAX:

[source, scala]
----
val factory: XMLInputFactory = XMLInputFactory.newInstance
factory.setProperty(XMLInputFactory.IS_REPLACING_ENTITY_REFERENCES, false)
----
... except the entities get delivered through a dedicated event,
`EntityReference`, not as `Characters`...

With the real XML parser my fenced code blocks get mangled;
setting another property took care of that:

[source, scala]
----
factory.setProperty(XMLInputFactory.IS_COALESCING, true)
----

... but counter-acted the one that parses the entities!

So, I need to coalesce the characters myself,
and incorporate entities into the result!


Using the real XML parser, I discovered that the custom `404.html` file that I used on my personal website for the last two
years, and which I found when originally setting up Jekyll,
was not valid XML/HTML:
it has two root elements (`<style>` and `<div>`)!
It is possible that Jekyll's parser does the right thing,
but ZIO Blocks XML parser parses the first root element and silently
ignores the rest, which is _definitely_ not the right thing.

=== HTML

=== Git

[#todo]
== TODO

=== XML Writer

Rewrite to make sure that text abutting an element does not get separated from it.

Unify `Markup.stop` and `XmlWriter.protected`

=== CSS
- unify approach to producing horizontal lines: `<hr>` or CSS border
- escape URLs etc.?
- alias languages unknown to Highlights.js to known ones - or to autodetect
- style code blocks so that they do not break up into stripes when not recognized by Highlights.js
- remove unneeded classes
- unify and clean up the CSS

=== Embedding
- do PDF embedding - with `<object>`, `<iframe>` or?
- do video embedding?
- recognize more audio/image types; is there some registry available?
- treat `<img>` as a link element also?

=== JS Libraries
- unify the CDNs used
- unify the approach to what goes into the head and what - into the body
- do I need `defer` and/or `async` attributes on my `script` tags?

=== Errors
- introduce a notion of warning
- generate error report page(s):
* broken links
* inconsistent titles

=== HTML and XML
- verify that I use `BooleanAttribute` and `BooleanValue` correctly
- if I need prefixed names like `tei:p`, ask ZIO Blocks people to allow them in HTML
- mention ZIO Blocks HTML optional attributes in its documentation.

=== Git Integration
- exclude files excluded by `.gitignore`
- retrieve Git creation/modification dates using JGit
- ask Obsidian developers to make file moves visible to Git if the vault is a Git repository

=== Sitemap and Feed
- generate RSS feed
- add whatever is needed for the feed to the `<head>`
- generate sitemap
- add whatever is needed for the feed to the `<head>`
- implement SEO - or is just the page title in the `<head>` all I need?
- whatever the feed post summaries end up being, conditionally add same as post excerpt to the post list
