= Publisher

Generate, serve and publish websites.

== Motivation

=== Jekyll finally pissed me off

When I listed TODO link  unresistable to any programmer urge to
write certain kinds of systems, I neglected to mention
a static site generator.

I've been using Jekyll since I migrated my blog from Blogger TODO when;
I then moved my notes from Roam into Obsidian
TODO when link and merged them into the static site with my blog;
that required customizing my Jekyll setup
TODO move Jekyll customization notes into the Jekyll page and link it here.

In March 2026, my site stopped publishing;
error messages were meaningless, and it took a lot of time
to figure out what is the problem by deleting files until it went away.
It turned out that Jekyll plugin I used for handling wiki links TODO link
breaks when an `index` page contains a wiki link (e.g., a [[TODO]]).
Previous communications with the author of the plugin made it clear
that he considers Jekyll to be a legacy system
(but it remained unclear what is the suggested replacement).

At this point, I looked at a few of the modern static site generators
like 11ty TODO link - and decided to write my own ;)

=== New Possibilities

It occurred to me that if I write my own site generator,
I can make it Obsidian-aware:

- it can read Obsidian configuration
- it can publish daily notes as dated blog posts

It also occurred to me that I can make alter-rebbe.org TODO link,
a site where I publish some archive documents in the TEI format
static (again) -
if I add support for TEI to my generator:

- link resolution
- facsimiles
- multi-lingual names

It also occurred to me that I can add publishing to X Articles -
if X ever makes an API for that. This would allow me
to own my blog - and at the same time use X ;)

=== Opinionated

Since I am writing this site generator for my own use,
it is going to be opinionated:

- everything is written in Scala
- no plugins
- no SCSS
- no template languages
- no layouts

TODO expound

=== Titles and File Names
Jekyll relies on page titles being given explicitly in the front matter
and ignores the file names; I had to use a TODO Obsidian plugin to set the
titles from the file names to communicate them to Jekyll;
as a result, pages where the title is different from the file name
(e.g., `index` pages)
had to be marked with TODO in their front matter to disable this plugin
from setting the front matter title.

My plugin uses both the front matter title and the file name for
link resolution, so I can remove this Obsidian plugin and
redundant front matter titles which are the same as the file name,
and set the title in the front matter only when it is different from the file name.

Obsidian uses file names exclusively and ignores the front matter title;
for link resolution to use front matter titles also,
TODO Obsidian plugin needs to be installed.

== Farewell, Jekyll

Events of 2026:

- Mar 17: My Jekyll setup (wiki-refs plugin) broke down
- Mar 20: I created my site publisher repository
- I became aware of ZIO Blocks Yaml released on Mar 11 and ZIO Blocks Markdown released on Jan 30
- Mar 22: I filed ZIO Blocks pull request
- Apr 30: I switched my personal website to use my site publisher vis GitHub Actions Workflow
- May 04: I removed all traces of Jekyll from my personal website
- May 06: I became aware of the ZIO Blocks HTML that was added on Apr 25-May 01, and started switching to it from my home-grown HTML DSL
- May 07: switched


First milestone for this project is to replace Jekyll on my personal website.
In under two month and a little less than 2000 lines of Scala code,
I have:

- no support for paginating the post list, which I did not use with Jekyll anyway;
- instead of the Ruby code highlighter Rouge, my publisher uses Highlights.js; it loads only the language modules used in the page; TODO unsupported language mapping...

TODO

- Add Mermaid diagrams and make sure that Highlights.js does not interfere
- Alias languages unknown to Highlights.js to known ones - or to autodetect
- Look into server-side highlighting

- while I did manage to list children pages using Jekyll,
I never figured out how to list subdirectories;
with my own publisher this is not a problem ;)

- Jekyll ignores Markdown files without front matter; I do not;
- wiki links
- link resolution
- front-matter defaults auto-added pages;
- header pages are configured in their frontmatter, with FA icons (and defaults) ;)
- transclusion
- directory navigation: up, prev, next; TODO;
- path navigation; TODO;
- title transplantation; TODO;
- insertion of missing index pages;

Write about all the plugins I used:

- jekyll-optional-front-matter
- jekyll-sitemap
- jekyll-feed
- jekyll-mentions
- jekyll-avatar
- jekyll-wikirefs

== Implementation

At exactly the same time I became aware of the ZIO Blocks project,
which just added support for a few data formats that I need.

=== JSON
I use ZIO Blocks JSON support to read Obsidian configuration files.

=== Yaml

=== Markdown

Pipeline:

- Markdown text
- Markdown AST
- HTML text
- HTML AST

I need HTML AST for post-processing like calculating page structure, resolving links to sections and blocks, transclusion, chunking, adding TOC,
and prefer to use it for all post-processing
like HTML layout for the browser and PDF generation.

Converting ZIO Blocks Markdown AST to XML AST proved inconvenient
(e.g., for reasons unknown, there are two flavours of each `Inline` subclass); it also turned out to be impossible, since
Markdown allows embedding HTML,
and since opening and closing tags of the same HTML element
may end up in different Markdown AST nodes,
I can not go directly from Markdown AST to HTML AST -
I have to go through HTML text.

Parsing Markdown with ZIO Blocks parser and writing it to XML text
turned out to be inconvenient: ZIO Blocks Markdown writer
produces unclosed tags like `br` and `hr`,
which are not valid XML and thus can not be parsed into XML AST.
I had to write my own writer for ZIO Blocks Markdown AST.

Converting Markdown text to XML AST using ZIO Blocks Markdown parser
still turned out impossible, since it parses nested lists incorrectly:

[source]
----
- l1
  - l2
----

parses exactly the same as

[source]
----
- l1
- l2
----

// ZIO Blocks Markdown parse parses nested lists incorrectly; see https://github.com/zio/zio-blocks/issues/1377
// FlexMark WikiLink extension is useless to me:
// - it sets the content of the rendered HTML 'a' element when there is no | in the link;
// - it prefixes the href with the dashes corresponding in number to the spaces after the |...
//
// Unlike ZIO Blocks Markdown HTML renderer,
// which I had to fork to ensure that resulting HTML is valid XML
// (no unclosed tags like 'br', 'hr', 'input' and 'img'; attributes have values etc.),
// FlexMark renders valid XML out of the box.
// I may need to add some extensions to handle GitHub task lists and such...

I had to switch to the industry-standard FlexMark parser.

It can be configured to
pair some - but not all - of the tags,
so direct Markdown AST to HTML AST is not possible with FlexMark either.

Since I insist on the end result being HTML AST,
invalid XML (e.g., unclosed 'br' elements)
embedded in the Markdown text is not supported.

I process wiki links and Kramdown TOC marker in post-processing.

=== XML

As a part of the OpenTorah project, I developed a custom
XML pretty-printer for the Scala XML AST;
I need to write one for the ZIO Blocks XML AST,
since the XML writer provided by ZIO Blocks is broken:
when used with "pretty", it

- inserts spaces between book titles and quotes around them;
- destroys the formatting of the code blocks;

when used with "default", in addition to producing
non-human-readable text, it:

- does not insert spaces between text and elements;
- mangles the formatting of the code blocks if there are spaces at the beginning of the lines after the first one.

With my own XML writer, I can also ensure that the empty elements
that cause problems with the browsers when they are self-closed
(script, data, span) are not -
without inserting comments into them, which is ugly.

See that the following renders as is:

[source,markdown]
----
val escaped = userInput.replace("<", "&lt;").replace(">", "&gt;")
----

Parse notes (:::note...:::)

== TODO

Mention ZIO Blocks HTML optional attributes in its documentation.

ZIO Blocks HTML does not allow prefixed element names;
deal with it for TEI - or ask for lenience ;)

Add FrontMatter "post: true" to control publishing arbitrary notes as posts.

// TODO file named after directory is its index!

// TODO sort the pages in transclusion order and transclude

Finish feed and sitemap.

// TODO include (some of the) SyntheticPages in the link resolution
// or introduce (non-transcludable) Link.ToAnchor?

Title of an `index.html` page should be the same as the title of the parent page. This one simple consideration pushes me towards the approach
reminiscent of the one I took with my TEI website:
path to a page should lead not through names, but trough *pages*!

Another feature of my TEI approach - "facets" of a page -
also arises naturally: there are pages that produce XML instead of HTML (feed.xml); there are pages that produce text (robots.txt);
there are pages that in addition to HTML produce chunked HTML and PDF.

Rewrite the XML leaving code blocks with unsupported languages for Highlights.js to auto-discover.

Wiki links in Obsidian:

- are they case-sensitive?
- do they take into account file name, title property, document title?
- how do they look in the file if name reference is ambiguous?
- can they be split between the lines?
- do they support any kind of agglutination?
- handle categories; they can be wiki links?!
- handle permalinks and multi-name redirects
- handle aliases

CLI:

- package as a GitHub Action
- serve with filesystem watch
- publish site into a bucket


Additional markup types:

- TEI (including facsimiles and raw TEI)
- AsciiDoc?
- DocBook??
- ReStructured Text?

PDF:

- danfickle/openhtmltopdf: An HTML to PDF library for the JVM. Based on Flying Saucer and Apache PDF-BOX 2. With SVG image support. Now also with accessible PDF support (WCAG, Section 508, PDF/UA)! · GitHub [https://share.google/UiGeZVUcInZur8zNF](https://share.google/UiGeZVUcInZur8zNF)
- [https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd](https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd)
