= Publisher

Generate, serve and publish websites.

== Motivation

=== Jekyll finally pissed me off

When I listed TODO link  unresistable to any programmer urge to
write certain kinds of systems, I neglected to mention
a static site generator.

I've been using Jekyll since I migrated my blog from Blogger TODO when;
I then moved my notes from Roam into Obsidian
TODO when link and merged them into the static site with my blog;
that required customizing my Jekyll setup
TODO move Jekyll customization notes into the Jekyll page and link it here.

In March 2026, my site stopped publishing;
error messages were meaningless, and it took a lot of time
to figure out what is the problem by deleting files until it went away.
It turned out that Jekyll plugin I used for handling wiki links TODO link
breaks when an `index` page contains a wiki link (e.g., a [[TODO]]).
Previous communications with the author of the plugin made it clear
that he considers Jekyll to be a legacy system
(but it remained unclear what is the suggested replacement).

At this point, I looked at a few of the modern static site generators
like 11ty TODO link - and decided to write my own ;)

=== New Possibilities

It occurred to me that if I write my own site generator,
I can make it Obsidian-aware:

- it can read Obsidian configuration
- it can publish daily notes as dated blog posts

It also occurred to me that I can make alter-rebbe.org TODO link,
a site where I publish some archive documents in the TEI format
static (again) -
if I add support for TEI to my generator:

- link resolution
- facsimiles
- multi-lingual names

It also occurred to me that I can add publishing to X Articles -
if X ever makes an API for that. This would allow me
to own my blog - and at the same time use X ;)

=== Opinionated

Since I am writing this site generator for my own use,
it is going to be opinionated:

- everything is written in Scala
- no plugins
- no SCSS
- no template languages
- no layouts

TODO expound

=== Titles and File Names
Jekyll relies on page titles being given explicitly in the front matter
and ignores the file names; I had to use a TODO Obsidian plugin to set the
titles from the file names to communicate them to Jekyll;
as a result, pages where the title is different from the file name
(e.g., `index` pages)
had to be marked with TODO in their front matter to disable this plugin
from setting the front matter title.

My plugin uses both the front matter title and the file name for
link resolution, so I can remove this Obsidian plugin and
redundant front matter titles which are the same as the file name,
and set the title in the front matter only when it is different from the file name.

Obsidian uses file names exclusively and ignores the front matter title;
for link resolution to use front matter titles also,
TODO Obsidian plugin needs to be installed.

== Implementation

At exactly the same time I became aware of the ZIO Blocks project,
which just added support for a few data formats that I need.

=== JSON
I use ZIO Blocks JSON support to read Obsidian configuration files.

=== Yaml

=== Markdown

Pipeline:

- Markdown text
- Markdown AST
- HTML text
- HTML AST

I need HTML AST for post-processing like calculating page structure, resolving links to sections and blocks, transclusion, chunking, adding TOC,
and prefer to use it for all post-processing
like HTML layout for the browser and PDF generation.

Converting ZIO Blocks Markdown AST to XML AST proved inconvenient
(e.g., for reasons unknown, there are two flavours of each `Inline` subclass); it also turned out to be impossible, since
Markdown allows embedding HTML,
and since opening and closing tags of the same HTML element
may end up in different Markdown AST nodes,
I can not go directly from Markdown AST to HTML AST -
I have to go through HTML text.

Parsing Markdown with ZIO Blocks parser and writing it to XML text
turned out to be inconvenient: ZIO Blocks Markdown writer
produces unclosed tags like `br` and `hr`,
which are not valid XML and thus can not be parsed into XML AST.
I had to write my own writer for ZIO Blocks Markdown AST.

Converting Markdown text to XML AST using ZIO Blocks Markdown parser
still turned out impossible, since it parses nested lists incorrectly:

[source]
----
- l1
  - l2
----

parses exactly the same as

[source]
----
- l1
- l2
----

I had to switch to the industry-standard FlexMark parser.

It can be configured to
pair some - but not all - of the tags,
so direct Markdown AST to HTML AST is not possible with FlexMark either.

Since I insist on the end result being HTML AST,
invalid XML (e.g., unclosed 'br' elements)
embedded in the Markdown text is not supported.

=== XML

As a part of the OpenTorah project, I developed a custom
XML pretty-printer for the Scala XML AST;
I need to write one for the ZIO Blocks XML AST,
since the XML writer provided by ZIO Blocks is broken:
when used with "pretty", it

- inserts spaces between book titles and quotes around them;
- destroys the formatting of the code blocks;

when used with "default", it:

- does not insert spaces between text and elements;
- mangles the formatting of the code blocks if there are spaces at the beginning of the lines after the first one;
- produces non-pretty results ;)

With my own XML write, I can also ensure that the empty elements
that cause problems with the browsers when they are self-closed
(script, data, span) are not -
without inserting comments into them, which is ugly.

== Farewell, Jekyll

First milestone for this project is to replace Jekyll on my personal website. Some differences between the new publisher and Jekyll:

- no support for paginating the post list, which I did not use with Jekyll anyway;
- instead of the Ruby code highlighter Rouge, my publisher uses Highlights.js;
- while I did manage to list children pages using Jekyll,
I never figured out how to list subdirectories;
with my own publisher this is not a problem ;)
- Jekyll ignores Markdown files without front matter; I do not;
- I added directory navigation: up, prev, next; TODO;
- I added path navigation; TODO;
- I added title transplantation; TODO;
- insertion of missing index pages; TODO;

== TODO

Title of an `index.html` page should be the same as the title of the parent page. This one simple consideration pushes me towards the approach
reminiscent of the one I took with my TEI website:
path to a page should lead not through names, but trough *pages*!

Another feature of my TEI approach - "facets" of a page -
also arises naturally: there are pages that produce XML instead of HTML (feed.xml); there are pages that produce text (robots.txt);
there are pages that in addition to HTML produce chunked HTML and PDF.

Add post hierarchy browser by year, month, day.


Wiki links in Obsidian:

- are they case-sensitive?
- do they take into account file name, title property, document title?
- how do they look in the file if name reference is ambiguous?
- can they be split between the lines?
- do they support any kind of agglutination?
- handle categories; they can be wiki links?!
- handle permalinks and multi-name redirects
- handle aliases

CLI:

- package as a GitHub Action
- serve with filesystem watch
- publish site into a bucket


Additional markup types:

- TEI (including facsimiles and raw TEI)
- AsciiDoc?
- DocBook??
- ReStructured Text?

PDF:

- danfickle/openhtmltopdf: An HTML to PDF library for the JVM. Based on Flying Saucer and Apache PDF-BOX 2. With SVG image support. Now also with accessible PDF support (WCAG, Section 508, PDF/UA)! · GitHub [https://share.google/UiGeZVUcInZur8zNF](https://share.google/UiGeZVUcInZur8zNF)
- [https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd](https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd)
